### ISSUE TITLE
pytest scans every py file for tests

### ISSUE THREAD

**Issue by gilesknap** [dls-controls/dls-python3-skeleton#16]
This caused me issues with a utility script blowing up pytest.

This fixed it for me - but will this have any unwanted consequences?

In setup.cfg:
```
[tool:pytest]
testpaths =
    tests
```

**Comment by coretl** [comment]
It seems reasonable to limit the places pytest looks for tests, but we potentially have tests in 3 places:
- Unit tests in `tests`
- Doctests in docstrings in `src`
- Doctests in documentation in `docs`
Adding those 3 directories seems to work

**Comment by coretl** [comment]
https://github.com/dls-controls/scanspec/commit/8190f0e224570fc203d4a6fff4f19ab1e1b7a347
