### ISSUE TITLE
Apostrophes in author & author email result in broken setup.cfg

### ISSUE THREAD

**Issue by garryod** [dls-controls/dls-python3-skeleton#22]
When `Firstname Lastname` and `email@address.com` are substituted with an author name or email which includes an apostrophe a broken `setup.cfg` is produced in which erroneous strings exist

**Comment by coretl** [comment]
Maybe we should be using `ConfigParser.write` to set those fields rather than a dumb search and replace? They're only set in `setup.cfg`, so there's only one place to look

**Comment by garryod** [comment]
Having investigated the usage of `ConfigParser` for editing of `.cfg` & `.ini` files and escaping of strings during substitution updating of the template appears to be the best option despite causing downstream merge conflicts.

Use of `ConfigParser` or escaping of strings would both require a substantial increase in code complexity in order to maintain the current contract with template writers
