### ISSUE TITLE
Make keeping a changelog easier

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/dls-python3-skeleton#7]
I was having a look at apischema's changelog:
https://github.com/wyfo/apischema/releases

And was impressed. So I asked how it was generated:
https://github.com/wyfo/apischema/discussions/315

It seems to fit with the workflow I am leaning towards (PR for each feature/bugfix, only minor edits to master), so I was wondering whether to adopt it instead of CHANGELOG.rst?

**Comment by thomascobb** [comment]
@aawdls what do you reckon?

**Comment by aawdls** [comment]
In previous discussions we've highlighted that manual input in a changelog is the best way to ensure it is useful,

There is a step where you can edit the generated release notes, so I think this is a good combination of the automated part to save the drudgery of collecting the info yourself, and the possibility to edit to clean it up.

It's certainly better than just having to look at the raw list of PRs.

**Comment by thomascobb** [comment]
Ok, I've squashed and pushed `skeleton` with this change
